version: 2

models:
  - name: average_usage
    description: "Analyzes bike usage percentage per station and ranks stations by usage."
    columns:
      - name: station_id
        description: "Unique identifier for the bike station."
        tests:
          - unique
          - not_null

      - name: avg_usage_percentage
        description: "Percentage of slots filled."
        tests:
          - not_null

      - name: station_name
        description: "Name of the bike station."
        tests:
          - not_null

  - name: bike_change
    description: "Analyzes the changes in bike availability at stations over time using window functions."
    columns:
      - name: station_id
        description: "Unique identifier for the bike station."
        tests:
          - unique
          - not_null

      - name: station_name
        description: "Name of the bike station."
        tests:
          - not_null

      - name: avg_change_in_free_bikes
        description: "The average change in bike availability at each station."
        tests:
          - not_null

  - name: district_std_dev
    description: "Analyzes the standard deviation of bike and slot availability across districts."
    columns:
      - name: district
        description: "The district where bike stations are located."
        tests:
          - not_null
          - unique

      - name: bike_availability_stddev
        description: "The standard deviation of bike availability in the district, rounded to 4 decimal places."
        tests:
          - not_null

      - name: slot_availability_stddev
        description: "The standard deviation of slot availability in the district, rounded to 4 decimal places."
        tests:
          - not_null

      - name: station_count
        description: "The number of stations in the district."
        tests:
          - not_null
